n = input('\033[4;35mDigite algo:\033[m ')
print('O tipo primitivo disso é:', type(n))
print('Só tem espaços?',n.isspace())
print('É um número?',n.isnumeric())
print('É alfabético?',n.isalpha())
print('É alfanumérico?',n.isalnum())
print('É tudo maiúsculo?',n.isupper())
print('É tudo minúsculo?',n.islower())
print('Está capitalizado?',n.istitle())
